# Define the base image dynamically
ARG BASE_IMAGE=rust:slim-bookworm
FROM ${BASE_IMAGE}
ARG BASE_IMAGE  
ARG DEBIAN_FRONTEND=noninteractive

# RUN apt-get update; \
#     PKGS="jq curl sudo git make wget build-essential openssl pkg-config libssl-dev ca-certificates lsb-release gnupg2"; \
#     if [ "${BASE_IMAGE}" != "rust:slim-trixie" ]; then \
#         PKGS="$PKGS software-properties-common"; \
#     else \
#         echo "Skipping software-properties-common for base ${BASE_IMAGE}"; \
#     fi; \
#     apt-get install -y --no-install-recommends $PKGS; \
#     rm -rf /var/lib/apt/lists/*


RUN apt-get update; \
    apt-get install -y --no-install-recommends software-properties-common jq curl sudo git make wget build-essential openssl pkg-config libssl-dev ca-certificates lsb-release gnupg2; \
    rm -rf /var/lib/apt/lists/*

# RUN if [ "${BASE_IMAGE}" == "ubuntu:22.04" || "${BASE_IMAGE}" == "ubuntu:24.04" ]; then \
#         curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable; \
#         rustup default stable; \
#     fi

# RUN apt-get update; \
#     if [ "$BASE_IMAGE" != "ubuntu:24.04" ]; then \
#         apt-get install -y --no-install-recommends software-properties-common; \
#     else \
#         echo "Skipping software-properties-common for base ${BASE_IMAGE}"; \
#     fi; \
#     rm -rf /var/lib/apt/lists/*


# RUN useradd -ms /bin/bash documentdb -G sudo
# RUN echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/no-pass-ask

RUN useradd -ms /bin/bash documentdb -G sudo
RUN mkdir -p /etc/sudoers.d && echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/no-pass-ask

USER documentdb
WORKDIR /home/documentdb/code

COPY . /home/documentdb/code

RUN sudo chmod +x /home/documentdb/code/scripts/*.sh
RUN /home/documentdb/code/scripts/install_llvm.sh

# Install rustup (which includes rustc and cargo) in user directory
ENV RUSTUP_HOME=/home/documentdb/.rustup
ENV CARGO_HOME=/home/documentdb/.cargo
RUN mkdir -p $RUSTUP_HOME && mkdir -p $CARGO_HOME
ENV PATH=$PATH:$CARGO_HOME/bin

# RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain stable
RUN /home/documentdb/code/scripts/install_rustup.sh --install-toolchain
# RUN rustup default stable

# RUN rustup default stable
RUN cargo install cargo-deb

RUN sudo chown -R documentdb:documentdb /home/documentdb/code

WORKDIR /home/documentdb/code/pg_documentdb_gw

RUN CARGO_MANIFEST_DIR=/home/documentdb/code/pg_documentdb_gw cargo build --profile=release-with-symbols

# Create /output directory and set permissions for the documentdb user
USER root
RUN mkdir -p /output && chown documentdb:documentdb /output
USER documentdb

# # Output the .deb file to /output
# RUN cargo deb --no-build --profile=release-with-symbols --output /output/

# # Default command to keep the container running
# CMD ["tail", "-f", "/dev/null"]
CMD ["cargo", "deb", "--no-build", "--profile=release-with-symbols", "--output", "/output/"]